keys:
  - &work age1pd03awq8rz2mmn8gzdfytz06jvalpxl36q9shdr2a4fk9zswygss8d4mw9
  - &mw age1epe73msaedxtnz94emjydhvcsz9na70wdrrftme2msm5n0anr3gsavsj4v
creation_rules:
  - path_regex: .env.enc
    key_groups:
      - age:
          - *mw
          - *work
