"""apartments.num_rooms to numeric

Revision ID: 05d40a5d7687
Revises: 89cc4607a38d
Create Date: 2025-11-11 14:23:52.969083

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "05d40a5d7687"
down_revision = "89cc4607a38d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "apartment",
        "num_rooms",
        existing_type=sa.INTEGER(),
        type_=sa.Numeric(precision=2, scale=1),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "apartment",
        "num_rooms",
        existing_type=sa.Numeric(precision=2, scale=1),
        type_=sa.INTEGER(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
