"""settings: email optional

Revision ID: 4052c231daf9
Revises: bd7a5de145fc
Create Date: 2025-11-07 11:39:27.660891

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "4052c231daf9"
down_revision = "bd7a5de145fc"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "settings", "email", existing_type=sa.VARCHAR(length=255), nullable=True
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "settings", "email", existing_type=sa.VARCHAR(length=255), nullable=False
    )
    # ### end Alembic commands ###
