"""Refactor html pages into separate table

Revision ID: 4ccf8655fe4f
Revises: cd45f2b6b14d
Create Date: 2026-01-05 18:13:46.983148

"""

import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "4ccf8655fe4f"
down_revision = "cd45f2b6b14d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "apartmentpage",
        sa.Column("url", sqlmodel.sql.sqltypes.AutoString(length=2048), nullable=False),
        sa.Column("content", sa.Text(), nullable=True),
        sa.Column("scraped_at", sa.DateTime(), nullable=False),
        sa.Column("inserted_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("apartment_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["apartment_id"],
            ["apartment.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.alter_column(
        "apartment",
        "num_rooms",
        existing_type=sa.NUMERIC(precision=2, scale=1),
        nullable=True,
    )
    op.alter_column(
        "apartment",
        "address",
        existing_type=sa.VARCHAR(length=512),
        type_=sa.Text(),
        existing_nullable=True,
    )
    op.drop_column("apartment", "scraped_html")
    op.drop_column("apartment", "scraped_at")
    op.drop_column("apartment", "url")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "apartment",
        sa.Column("url", sa.VARCHAR(length=2048), autoincrement=False, nullable=False),
    )
    op.add_column(
        "apartment",
        sa.Column(
            "scraped_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
    )
    op.add_column(
        "apartment",
        sa.Column("scraped_html", sa.TEXT(), autoincrement=False, nullable=True),
    )
    op.alter_column(
        "apartment",
        "address",
        existing_type=sa.Text(),
        type_=sa.VARCHAR(length=512),
        existing_nullable=True,
    )
    op.alter_column(
        "apartment",
        "num_rooms",
        existing_type=sa.NUMERIC(precision=2, scale=1),
        nullable=False,
    )
    op.drop_table("apartmentpage")
    # ### end Alembic commands ###
