"""Initial migration

Revision ID: 510058938db0
Revises:
Create Date: 2025-11-11 11:22:23.293653

"""

import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic import op

# revision identifiers, used by Alembic.
revision = "510058938db0"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "apartment",
        sa.Column(
            "title", sqlmodel.sql.sqltypes.AutoString(length=512), nullable=False
        ),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("rating", sa.Integer(), nullable=True),
        sa.Column("num_rooms", sa.Integer(), nullable=False),
        sa.Column(
            "address", sqlmodel.sql.sqltypes.AutoString(length=512), nullable=False
        ),
        sa.Column("posted_at", sa.DateTime(), nullable=False),
        sa.Column("area_sqm", sa.Float(), nullable=False),
        sa.Column("construction_year", sa.Integer(), nullable=False),
        sa.Column("num_bathrooms", sa.Integer(), nullable=False),
        sa.Column("floor", sa.Integer(), nullable=False),
        sa.Column("maintenance_fee", sa.Float(), nullable=False),
        sa.Column("has_commission", sa.Boolean(), nullable=False),
        sa.Column("posting_id", sa.Integer(), nullable=False),
        sa.Column(
            "seller_object_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("price", sa.Float(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "settings",
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
        sa.Column(
            "cron_schedule", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("settings")
    op.drop_table("apartment")
    # ### end Alembic commands ###
