"""apartment remove title

Revision ID: 89cc4607a38d
Revises: c3052532d0f2
Create Date: 2025-11-11 11:47:27.188308

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "89cc4607a38d"
down_revision = "c3052532d0f2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("apartment", "title")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "apartment",
        sa.Column("title", sa.VARCHAR(length=512), autoincrement=False, nullable=False),
    )
    # ### end Alembic commands ###
