"""add some optional values

Revision ID: c3052532d0f2
Revises: c92214e1aab4
Create Date: 2025-11-11 11:30:16.289977

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "c3052532d0f2"
down_revision = "c92214e1aab4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "apartment", "construction_year", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column(
        "apartment", "has_commission", existing_type=sa.BOOLEAN(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "apartment", "has_commission", existing_type=sa.BOOLEAN(), nullable=False
    )
    op.alter_column(
        "apartment", "construction_year", existing_type=sa.INTEGER(), nullable=False
    )
    # ### end Alembic commands ###
