"""Apartment proper decimal

Revision ID: c92214e1aab4
Revises: 510058938db0
Create Date: 2025-11-11 11:27:08.916349

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "c92214e1aab4"
down_revision = "510058938db0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "apartment",
        "area_sqm",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        type_=sa.Numeric(precision=6, scale=1),
        existing_nullable=False,
    )
    op.alter_column(
        "apartment",
        "maintenance_fee",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        type_=sa.Numeric(precision=6, scale=2),
        existing_nullable=False,
    )
    op.alter_column(
        "apartment",
        "price",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        type_=sa.Numeric(precision=10, scale=2),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "apartment",
        "price",
        existing_type=sa.Numeric(precision=10, scale=2),
        type_=sa.DOUBLE_PRECISION(precision=53),
        existing_nullable=False,
    )
    op.alter_column(
        "apartment",
        "maintenance_fee",
        existing_type=sa.Numeric(precision=6, scale=2),
        type_=sa.DOUBLE_PRECISION(precision=53),
        existing_nullable=False,
    )
    op.alter_column(
        "apartment",
        "area_sqm",
        existing_type=sa.Numeric(precision=6, scale=1),
        type_=sa.DOUBLE_PRECISION(precision=53),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
