"""Make most apartment fields optional

Revision ID: cd45f2b6b14d
Revises: e4079e25a547
Create Date: 2026-01-05 16:10:12.949258

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "cd45f2b6b14d"
down_revision = "e4079e25a547"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "apartment", "address", existing_type=sa.VARCHAR(length=512), nullable=True
    )
    op.alter_column(
        "apartment", "posted_at", existing_type=postgresql.TIMESTAMP(), nullable=True
    )
    op.alter_column(
        "apartment",
        "area_sqm",
        existing_type=sa.NUMERIC(precision=6, scale=1),
        nullable=True,
    )
    op.alter_column(
        "apartment", "num_bathrooms", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column("apartment", "floor", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column(
        "apartment",
        "maintenance_fee",
        existing_type=sa.NUMERIC(precision=6, scale=2),
        nullable=True,
    )
    op.alter_column(
        "apartment", "posting_id", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column(
        "apartment", "seller_object_id", existing_type=sa.VARCHAR(), nullable=True
    )
    op.alter_column(
        "apartment",
        "price",
        existing_type=sa.NUMERIC(precision=10, scale=2),
        nullable=True,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "apartment",
        "price",
        existing_type=sa.NUMERIC(precision=10, scale=2),
        nullable=False,
    )
    op.alter_column(
        "apartment", "seller_object_id", existing_type=sa.VARCHAR(), nullable=False
    )
    op.alter_column(
        "apartment", "posting_id", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        "apartment",
        "maintenance_fee",
        existing_type=sa.NUMERIC(precision=6, scale=2),
        nullable=False,
    )
    op.alter_column("apartment", "floor", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column(
        "apartment", "num_bathrooms", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        "apartment",
        "area_sqm",
        existing_type=sa.NUMERIC(precision=6, scale=1),
        nullable=False,
    )
    op.alter_column(
        "apartment", "posted_at", existing_type=postgresql.TIMESTAMP(), nullable=False
    )
    op.alter_column(
        "apartment", "address", existing_type=sa.VARCHAR(length=512), nullable=False
    )
    # ### end Alembic commands ###
