"""save html with apatment

Revision ID: d06df53c7e6d
Revises: 05d40a5d7687
Create Date: 2025-11-11 14:57:08.826160

"""

import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic import op

# revision identifiers, used by Alembic.
revision = "d06df53c7e6d"
down_revision = "05d40a5d7687"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "apartment",
        sa.Column("scraped_html", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    )
    op.add_column("apartment", sa.Column("scraped_at", sa.DateTime(), nullable=False))
    op.add_column(
        "apartment",
        sa.Column("url", sqlmodel.sql.sqltypes.AutoString(length=2048), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("apartment", "url")
    op.drop_column("apartment", "scraped_at")
    op.drop_column("apartment", "scraped_html")
    # ### end Alembic commands ###
