"""html text

Revision ID: e4079e25a547
Revises: d06df53c7e6d
Create Date: 2025-11-11 14:58:54.289264

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "e4079e25a547"
down_revision = "d06df53c7e6d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "apartment",
        "scraped_html",
        existing_type=sa.VARCHAR(),
        type_=sa.Text(),
        nullable=True,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "apartment",
        "scraped_html",
        existing_type=sa.Text(),
        type_=sa.VARCHAR(),
        nullable=False,
    )
    # ### end Alembic commands ###
